### PR TITLE
fix: ruleset deprecated on `v3.18`

### LINKED ISSUE #7594: Dev: [php-cs-fixer] Detected deprecations in use
Detected deprecations in use:
- Option "annotation_exclude" for rule "final_internal_class" is deprecated and will be removed in version 4.0. Use "exclude" to configure PHPDoc annotations tags and attributes.
- Option "annotation_include" for rule "final_internal_class" is deprecated and will be removed in version 4.0. Use "include" to configure PHPDoc annotations tags and attributes.
- Rule "no_blank_lines_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.
- Rule "single_blank_line_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.

See https://github.com/codeigniter4/CodeIgniter4/actions/runs/5306306699/jobs/9603798768

### PR DESCRIPTION
**Pull request by ddevsr**
Closes https://github.com/codeigniter4/CodeIgniter4/issues/7594

Ref:
- https://cs.symfony.com/doc/rules/index.html#namespace-notation
- https://cs.symfony.com/doc/rules/class_notation/final_internal_class.html

### CODE REVIEW

**Comment by ddevsr** [comment]
@paulbalandan Unit test failed on nexus/cs-config?

**Comment by paulbalandan** [comment]
> @paulbalandan Unit test failed on nexus/cs-config?

No. I'll push the fix for ordered_class_elements. Please fix the ordering.

**Comment by paulbalandan** [comment]
Please rebase.

**Comment by ddevsr** [comment]
@paulbalandan done

**Comment by paulbalandan** [comment]
Thank you, @ddevsr

**Pull request merged**
